name: nodejs-api
services:
  nginx:
    build: ./nginx
    ports:
     - '8081:8081'
    depends_on:
     - api

    networks:
     - api_networks

  api:
    build: .
    command: ["npm", "start"]
    expose:
      - "5000"

    networks:
      - api_networks

   
networks:
  api_networks:
    driver: bridge