name: nodejs-api
services:
  nginx:
    build:
     context: .
     dockerfile: frontend.Dockerfile
    ports:
     - '8081:8081'
    depends_on:
     - api

    networks:
     - api_networks

  api:
    build: 
     context: .
     dockerfile: Dockerfile
    command: ["node", "src/server.js"]
    expose:
      - "5000"

    networks:
      - api_networks

   
networks:
  api_networks:
    driver: bridge