name: nodejs-api
services:
  nginx:
    build: /workspaces/deploy-api-nginx-prod/node-api-project/nginx
    ports:
     - '8081:8081'
    depends_on:
     - api

    networks:
     - api_networks

  api:
    build: .
    command: ["node", "src/server.js"]
    expose:
      - "5000"

    networks:
      - api_networks

   
networks:
  api_networks:
    driver: bridge